name: citymart
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.2
  barcode_scanner: ^3.0.1
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^2.2.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.5
  firebase_core: ^1.9.0
  firestore_search: ^0.1.6
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_google_places: ^0.2.8
  flutter_image_slideshow: ^0.1.2
  flutter_speed_dial: ^4.4.0
  fluttertoast: ^8.0.8
  geocoding: ^2.0.1
  geolocator: ^7.7.0
  get: ^4.3.8
  google_maps_flutter: ^2.0.9
  image_picker: ^0.8.4+1
  location: ^4.3.0
  path_provider: ^2.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.6
  share: ^2.0.4
  uuid: ^3.0.5
  adobe_xd: ^2.0.0+1
  flutter_svg: ^0.21.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stores.json
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
